#include <vector>
#include <string>
#include "floor_data.h"
#include "pickups_n_enemies.h"
#include "map/floor_art.h"
#include "map/floor_collisions.h"
#include "map/floor_colors.h"
#include "map/floor_events.h"
#include "map/floor_lights.h"
#include "map/floor_layout.h"
#include "map/floor_pickups.h"